import { google } from 'googleapis';
import { OAuth2Client } from 'google-auth-library';
import { GapMap } from './gemini.service';
import * as fs from 'fs';
import * as path from 'path';

export class GoogleDocsService {
  private docs: any;
  private drive: any;
  private oauth2Client: OAuth2Client;

  constructor() {
    // Load credentials
    const credentialsPath = path.join(process.cwd(), 'credentials.json');
    if (!fs.existsSync(credentialsPath)) {
      throw new Error('credentials.json not found. Please add your Google Cloud credentials.');
    }

    const credentials = JSON.parse(fs.readFileSync(credentialsPath, 'utf-8'));
    
    // Handle both "installed" and "web" credential formats
    const clientId = credentials.installed?.client_id || credentials.web?.client_id;
    const clientSecret = credentials.installed?.client_secret || credentials.web?.client_secret;
    const redirectUris = credentials.installed?.redirect_uris || credentials.web?.redirect_uris;
    
    if (!clientId || !clientSecret) {
      throw new Error('Invalid credentials.json format. Missing required fields.');
    }
    
    // For web applications, use a default redirect URI if not specified
    const redirectUri = redirectUris ? redirectUris[0] : 'http://localhost:3000/auth/callback';
    
    this.oauth2Client = new google.auth.OAuth2(
      clientId,
      clientSecret,
      redirectUri
    );

    // Load token if exists
    const tokenPath = path.join(process.cwd(), 'token.json');
    if (fs.existsSync(tokenPath)) {
      const token = JSON.parse(fs.readFileSync(tokenPath, 'utf-8'));
      this.oauth2Client.setCredentials(token);
    }

    this.docs = google.docs({ version: 'v1', auth: this.oauth2Client });
    this.drive = google.drive({ version: 'v3', auth: this.oauth2Client });
  }

  async createGapAnalysisReport(gapMap: GapMap): Promise<string> {
    try {
      // Create a new Google Doc
      const createResponse = await this.docs.documents.create({
        requestBody: {
          title: 'Gap Analysis Report'
        }
      });

      const documentId = createResponse.data.documentId;

      // Build the content
      const content = this.buildReportContent(gapMap);

      // Insert content into the document
      await this.docs.documents.batchUpdate({
        documentId: documentId,
        requestBody: {
          requests: [
            {
              insertText: {
                location: {
                  index: 1
                },
                text: content
              }
            },
            // Style the title
            {
              updateParagraphStyle: {
                range: {
                  startIndex: 1,
                  endIndex: 22 // "Gap Analysis Report\n"
                },
                paragraphStyle: {
                  namedStyleType: 'TITLE',
                  alignment: 'CENTER'
                },
                fields: 'namedStyleType,alignment'
              }
            }
          ]
        }
      });

      // Get shareable link
      await this.drive.permissions.create({
        fileId: documentId,
        requestBody: {
          role: 'reader',
          type: 'anyone'
        }
      });

      const docUrl = `https://docs.google.com/document/d/${documentId}/edit`;
      return docUrl;
    } catch (error: any) {
      throw new Error(`Failed to create Google Doc: ${error.message}`);
    }
  }

  private buildReportContent(gapMap: GapMap): string {
    const date = new Date().toLocaleDateString();
    
    return `Gap Analysis Report

Generated: ${date}

EXECUTIVE SUMMARY
${gapMap.analysis_summary}

TOPICS COMPETITOR CURRENTLY COVERS
${gapMap.topics_competitor_covers.map((topic, i) => `${i + 1}. ${topic}`).join('\n')}

IDENTIFIED CONTENT GAPS
${gapMap.identified_gaps.map((gap, i) => `${i + 1}. ${gap}`).join('\n')}

STRATEGIC OPPORTUNITIES
${gapMap.opportunities.map((opp, i) => `${i + 1}. ${opp}`).join('\n')}

---
Report generated by Gap Analysis Engine powered by Gemini AI
`;
  }

  getAuthUrl(): string {
    const SCOPES = [
      'https://www.googleapis.com/auth/documents',
      'https://www.googleapis.com/auth/drive.file'
    ];

    return this.oauth2Client.generateAuthUrl({
      access_type: 'offline',
      scope: SCOPES
    });
  }

  async getToken(code: string): Promise<void> {
    const { tokens } = await this.oauth2Client.getToken(code);
    this.oauth2Client.setCredentials(tokens);
    
    // Save token
    const tokenPath = path.join(process.cwd(), 'token.json');
    fs.writeFileSync(tokenPath, JSON.stringify(tokens));
  }
}
